spring:
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect : org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  zipkin:
     base-url: http://localhost:9411/      
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost      
      
file:
  upload:
    location: C:\fitness       
    
